version: "3"

services:
  nginx:
    container_name: nginx_container
    build: ./docker/nginx
    ports:
      - 8080:80
    links:
      - php
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge

  php:
    container_name: php_container
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/
    networks:
      - bridge

  db:
    container_name: mysql_container
    build: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=rate_the_books
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./opt/db/:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - bridge

networks:
  bridge: